merge devlopment to main branch
melkamu372/capstone-project pull request #1
Opened 2023-08-08 10:48 UTC by melkamu372

### Features added to devlopment branch

- add home page contents
- add about page contents
- add JavaScript to manipulate DOM elements
- add JavaScript events 
- add css styles for both pages
- add back ground images and icons

2023-08-08 13:01 UTC, muneebulrehman requested changes
Hi @melkamu372 , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- Great job styling the project.
- Clean code. No commented code.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-08 13:01 UTC, muneebulrehman commented on index.html
> +                </div>
As per the project requirements, this whole section should be created dynamically using JavaScript. You are populating the data using JS, however, in this case, even the HTML should be generated using a JS template or dom methods. Kindy do so and remove this html for the file.

2023-08-08 13:01 UTC, muneebulrehman commented on index.html
> +                </div>
As per the project requirements, each speaker should be wrapped in an `article` instead of `div`. That would make much more sense semantically since each speaker is independent of the other speakers.

2023-08-08 13:01 UTC, muneebulrehman commented on index.html
> +                        <img src="" alt="musician-img" class="musician-img" id="musician-img2">
As per the provided design, there should be a backdrop for all the images of the musicians. However, in your design, they are missing. I would recommend you add these. 

| Your design  | Behance design |
| ------------- | ------------- |
| ![image](https://github.com/melkamu372/capstone-project/assets/33268927/60d57dd7-16a7-4b81-9186-03ba4c3ea0ea) | ![image](https://github.com/melkamu372/capstone-project/assets/33268927/c67d476a-2755-46df-a87c-a23d440775b3) |

2023-08-08 13:01 UTC, muneebulrehman commented on index.html
> +    </footer>
- [ ] As per the provided design, the footer background color is not matching with that of the provided one. Kindly use the same color as in the provided design.

- [ ] Also, as per the provided design, the logo and the text should be in the center. Kindly align the footer content in the center.

| Your design  | Behance design |
| ------------- | ------------- |
| ![image](https://github.com/melkamu372/capstone-project/assets/33268927/1c03dee1-7c9d-43f2-bb6f-3a5e906d4acc) | ![image](https://github.com/melkamu372/capstone-project/assets/33268927/c3ddce9f-3338-490e-b226-d1cbf9aab68c) |

2023-08-08 13:01 UTC, muneebulrehman commented on about.html
> +    </footer>
- [ ] As per the provided design, the footer background color is not matching with that of the provided one. Kindly use the same color as in the provided design.

- [ ] Also, as per the provided design, the logo and the text should be in the center. Kindly align the footer content in the center.

| Your design  | Behance design |
| ------------- | ------------- |
| ![image](https://github.com/melkamu372/capstone-project/assets/33268927/d3230284-2b3e-4475-866c-0c99fbd37bdd) | ![image](https://github.com/melkamu372/capstone-project/assets/33268927/df386364-8baf-40c1-a840-531d8872866a) |

2023-08-08 13:01 UTC, muneebulrehman commented on about.html
> +
As per the provided template, the email should be of a different color and should be underlined. Kindly follow the project design and fix this issue. 

| Your design  | Behance design |
| ------------- | ------------- |
| ![image](https://github.com/melkamu372/capstone-project/assets/33268927/fa67bb28-ac5d-49aa-a82d-ed9b8b1f7e3c) | ![image](https://github.com/melkamu372/capstone-project/assets/33268927/413661f9-3d91-4883-a725-bdbb102a198b) |

2023-08-08 13:01 UTC, muneebulrehman commented on about.html
> +
As per the provided design template, there should be a partner section on the About page in the mobile version. However, this is missing in your design. Kindly add this before submitting for a re-review.

| Your design  | Behance design |
| ------------- | ------------- |
| ![image](https://github.com/melkamu372/capstone-project/assets/33268927/6c941a6a-dd8f-442b-b91c-5e40a2fdb95e) | ![image](https://github.com/melkamu372/capstone-project/assets/33268927/18ceef6b-5e2d-43ce-ac66-25ab28af57d3) |

2023-08-08 13:05 UTC, muneebulrehman commented on index.html
> +            </div>
As per the project requirements, each of these cards should be wrapped in an `article` instead of a `div`. That would make much more sense semantically since each of these cards is independent of each other.

2023-08-09 15:23 UTC, cynthiainga requested changes
Hi @melkamu372, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

 ## Highlights

- [ ] No linters errors ✔️ 
- [ ] Good design ✔️ 
- [ ] Correctg GitHub flow ✔️ 

 ## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-09 15:23 UTC, cynthiainga commented on index.html
> +    </footer>
- [ ] Good job so far but as mentioned by the previous reviewer kindly make sure your footer is aligned in the center 🙃 🙃 

Your design

<img width="888" alt="Screenshot 2023-08-09 at 17 33 05" src="https://github.com/melkamu372/capstone-project/assets/74501523/9b8620e9-c388-491d-86b8-30ed22698def">

Original design

<img width="981" alt="Screenshot 2023-08-09 at 17 32 34" src="https://github.com/melkamu372/capstone-project/assets/74501523/e59dda30-f9bc-4d46-88cb-8ad303742b39">

How it should look 👇🏾 

<img width="1076" alt="Screenshot 2023-08-09 at 18 18 17" src="https://github.com/melkamu372/capstone-project/assets/74501523/0bbda578-319c-47a0-8764-e192b19ef8eb">

2023-08-09 15:23 UTC, cynthiainga commented on about.html
> +                        <li class="nav-item"><a href="about.html" class="nav-link red">About</a></li>
- [Optional] Since this is already the About page, it doesn’t make sense for this link to be here instead, it could be better to change it to the home page link and change the text to `Home` so users can go back early to the home page because is not everyone who will know if the logo direct to the home page 🙃 😉

2023-08-09 15:23 UTC, cynthiainga commented on script/featured-data.js
> +const speaker = function () {
- [Optional] This is not the right way to name a function also when I open your file I get this 👉🏾  `Unexpected unnamed function.` Either you just declare your function like this `const speaker = () => {...}` or ` function speaker() {...}` 🙃

2023-08-09 15:40 UTC, melkamu372 commented on index.html
> +    </footer>
@cynthiainga   I do that before I changed based on the previous review . I did not understand what I do.

2023-08-09 19:33 UTC, levy002 approved these changes
## Hello @melkamu372 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Highlights
- No linter errors :heavy_check_mark: 
- Implemented all suggested changes :heavy_check_mark: 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 05:28 UTC, merged